#include "PluginEditor.h"
namespace{juce::Colour col(unsigned c){return juce::Colour(0xff000000u|c);}constexpr int keys[4]={'W','A','S','D'};constexpr unsigned colours[4]={0x61e5c8,0xb099ff,0xffcd69,0xff688c};
void text(juce::Graphics& g,juce::String s,juce::Rectangle<float> r,float size,juce::Colour c,int justify=juce::Justification::centred){g.setColour(c);g.setFont(juce::FontOptions(size,juce::Font::bold));g.drawText(s,r,int(justify),true);}}
BattleEditor::BattleEditor(BattleProcessor& p):AudioProcessorEditor(p),processor(p){setSize(1120,800);setResizable(true,true);setResizeLimits(1000,760,1600,1100);setWantsKeyboardFocus(true);
 for(int i=0;i<4;++i){addAndMakeVisible(picks[size_t(i)]);picks[size_t(i)].setButtonText("PICK "+juce::String(battle::mcs[size_t(i)].name));picks[size_t(i)].onClick=[this,i]{processor.home=i;int a=opponent.getSelectedId()-1;if(a==i){opponent.setSelectedId((i+1)%4+1);}repaint();};picks[size_t(i)].setWantsKeyboardFocus(false);opponent.addItem(battle::mcs[size_t(i)].name,i+1);}
 addAndMakeVisible(opponent);addAndMakeVisible(difficulty);opponent.setSelectedId(p.away.load()+1);opponent.onChange=[this]{processor.away=opponent.getSelectedId()-1;};difficulty.addItem("ROOKIE / relaxed chart",1);difficulty.addItem("BATTLE / eighth-note streaks",2);difficulty.addItem("HEADLINER / dense chart",3);difficulty.setSelectedId(p.difficulty.load()+1);difficulty.onChange=[this]{processor.difficulty=difficulty.getSelectedId()-1;};
 for(auto* b:{&start,&back,&pause}){addAndMakeVisible(*b);b->setWantsKeyboardFocus(false);}start.onClick=[this]{startBattle();};back.onClick=[this]{processor.stop();menu=true;syncVisibility();};pause.onClick=[this]{processor.pause(!processor.isPaused());pause.setButtonText(processor.isPaused()?"RESUME":"PAUSE");grabKeyboardFocus();};
 addAndMakeVisible(vocals);vocals.setToggleState(p.vocals.load(),juce::dontSendNotification);vocals.setWantsKeyboardFocus(false);vocals.onClick=[this]{processor.vocals=vocals.getToggleState();};addAndMakeVisible(volume);volume.setSliderStyle(juce::Slider::LinearHorizontal);volume.setTextBoxStyle(juce::Slider::TextBoxRight,false,45,22);volume.setRange(0,1,.01);volume.setValue(p.volume.load());volume.onValueChange=[this]{processor.volume=float(volume.getValue());};syncVisibility();startTimerHz(120);
}
void BattleEditor::startBattle(){if(processor.home.load()==processor.away.load()){processor.away=(processor.home.load()+1)%4;opponent.setSelectedId(processor.away.load()+1);}game.start(processor.home.load(),processor.away.load(),processor.difficulty.load(),unsigned(juce::Time::getMillisecondCounter()));held.fill(false);menu=false;lastCombo=0;processor.begin();pause.setButtonText("PAUSE");syncVisibility();grabKeyboardFocus();}
void BattleEditor::syncVisibility(){for(auto& p:picks)p.setVisible(menu);start.setVisible(menu);opponent.setVisible(menu);difficulty.setVisible(menu);back.setVisible(!menu);pause.setVisible(!menu);resized();repaint();}
void BattleEditor::resized(){int w=getWidth(),h=getHeight();int card=(w-100)/4;for(int i=0;i<4;++i)picks[size_t(i)].setBounds(30+i*(card+13),h-210,card-8,34);opponent.setBounds(30,h-125,260,34);difficulty.setBounds(310,h-125,320,34);start.setBounds(w-285,h-130,255,45);back.setBounds(20,14,130,30);pause.setBounds(162,14,90,30);vocals.setBounds(25,h-45,100,26);volume.setBounds(w-230,h-44,200,25);}
void BattleEditor::press(int lane){if(menu||processor.isPaused()||game.finished)return;int before=game.hits[0];game.press(lane,processor.battleTime());if(game.hits[0]>before){processor.vocalGain=1;processor.cue();}else if(game.activeSide()==0)processor.vocalGain=.4f;repaint();}
bool BattleEditor::keyPressed(const juce::KeyPress& k){if(menu)return false;int code=k.getKeyCode();for(int lane=0;lane<4;++lane)if(code==keys[lane]){if(!held[size_t(lane)]){held[size_t(lane)]=true;press(lane);}return true;}if(code=='P'||code==juce::KeyPress::escapeKey){processor.pause(!processor.isPaused());pause.setButtonText(processor.isPaused()?"RESUME":"PAUSE");return true;}return code==juce::KeyPress::spaceKey;}
bool BattleEditor::keyStateChanged(bool){if(menu)return false;for(int lane=0;lane<4;++lane){bool down=juce::KeyPress::isKeyCurrentlyDown(keys[lane]);if(!down)held[size_t(lane)]=false;else if(!held[size_t(lane)]){held[size_t(lane)]=true;press(lane);}}return true;}
void BattleEditor::focusLost(FocusChangeType){if(!menu&&!game.finished){processor.pause(true);pause.setButtonText("RESUME");held.fill(false);}}
void BattleEditor::mouseDown(const juce::MouseEvent&){if(!menu)grabKeyboardFocus();}
void BattleEditor::timerCallback(){if(!menu&&!processor.isPaused()&&!game.finished){int misses=game.misses[0];game.update(processor.battleTime());if(game.misses[0]>misses)processor.vocalGain=.4f;if(game.combo[0]>lastCombo&&game.combo[0]%8==0)processor.cue();lastCombo=game.combo[0];if(game.finished)processor.stop();}repaint();}
void BattleEditor::rapper(juce::Graphics& g,float x,float y,float scale,int mc,bool active,double t){float bob=active?float(std::sin(t*12.566)*3):0;auto c=col(battle::mcs[size_t(mc)].colour);float s=scale;auto skin=col(mc==0?0x9e7054:mc==1?0x79533f:mc==2?0xbe8965:0x80563e);
 g.setColour(col(0x060810).withAlpha(.5f));g.fillEllipse(x-35*s,y+110*s,75*s,16*s);g.setColour(col(0x171b29));g.fillRoundedRectangle(x-24*s,y+43*s,20*s,75*s,6*s);g.fillRoundedRectangle(x+5*s,y+43*s,20*s,75*s,6*s);g.setColour(col(0xe0e5ec));g.fillRoundedRectangle(x-27*s,y+111*s,30*s,12*s,3*s);g.fillRoundedRectangle(x+3*s,y+111*s,32*s,12*s,3*s);
 g.setColour(c.darker(.25f));g.fillRoundedRectangle(x-32*s,y-20*s+bob,66*s,77*s,10*s);g.setColour(skin);g.fillRoundedRectangle(x-21*s,y-62*s+bob,42*s,43*s,9*s);g.setColour(col(0x161620));if(mc==1){g.fillRoundedRectangle(x-26*s,y-68*s+bob,54*s,15*s,4*s);g.fillRect(x-15*s,y-73*s+bob,34*s,10*s);}else if(mc==3){for(int n=0;n<6;++n)g.fillRoundedRectangle(x-22*s+n*8*s,y-68*s+bob,7*s,34*s,3*s);}else g.fillRoundedRectangle(x-22*s,y-65*s+bob,45*s,12*s,4*s);
 g.setColour(col(0xeac765));g.drawEllipse(x-13*s,y-19*s+bob,28*s,30*s,2*s);g.setColour(skin);g.fillRoundedRectangle(x-48*s,y-8*s+bob,17*s,50*s,6*s);float handY=active?y-29*s+bob:y+20*s;g.drawLine(x+35*s,y-7*s+bob,x+49*s,handY,12*s);g.setColour(col(0x232936));g.drawLine(x+49*s,handY,x+58*s,handY-17*s,5*s);g.setColour(col(0xd7dce4));g.fillEllipse(x+53*s,handY-24*s,12*s,12*s);g.setColour(juce::Colours::black);g.fillEllipse(x-11*s,y-45*s+bob,4*s,4*s);g.fillEllipse(x+8*s,y-45*s+bob,4*s,4*s);
}
void BattleEditor::stage(juce::Graphics& g,juce::Rectangle<float> r,bool preview){double t=preview?juce::Time::getMillisecondCounterHiRes()*.001:game.time;float x=r.getX(),y=r.getY(),w=r.getWidth(),h=r.getHeight();g.setGradientFill(juce::ColourGradient(col(0x171129),x,y,col(0x050910),x,y+h,false));g.fillRect(r);
 for(int side:{-1,1}){juce::Path beam;float bx=x+w*(side<0?.15f:.85f);beam.startNewSubPath(bx,y);beam.lineTo(bx+side*100,y+h);beam.lineTo(bx-side*190,y+h);beam.closeSubPath();g.setColour(col(side<0?0x7a45ce:0x1cd4c2).withAlpha(.1f));g.fillPath(beam);}
 // An on-stage semicircle of listeners and a packed floor audience.
 for(int row=0;row<2;++row)for(int n=0;n<25;++n){float px=x+24+n*(w-48)/24,py=y+h*.32f+row*23+float(std::sin(t*5+n)*3);g.setColour(col((n+row)%2?0x404256:0x292b3f));g.fillRoundedRectangle(px-8,py,16,34,5);g.setColour(col((n+row)%3?0x77543e:0xad8263));g.fillEllipse(px-7,py-12,14,14);}
 g.setColour(col(0x252039));g.fillRect(x,y+h*.62f,w,h*.38f);g.setColour(col(0xa366ff));g.fillRect(x,y+h*.62f,w,2.f);text(g,"THE UNDERGROUND",{x+w*.26f,y+16,w*.48f,30},22,col(0xbba3e8));
 int hm=preview?processor.home.load():game.home,am=preview?processor.away.load():game.away;float scale=std::min(1.05f,h/250);rapper(g,x+w*.28f,y+h*.48f,scale,hm,!preview&&game.activeSide()==0,t);rapper(g,x+w*.72f,y+h*.48f,scale,am,!preview&&game.activeSide()==1,t);
 for(int n=0;n<35;++n){float px=x+n*(w/34),py=y+h-15+float(std::sin(t*6+n)*5);g.setColour(col(0x080912));g.fillEllipse(px-9,py-8,18,18);g.fillRoundedRectangle(px-15,py+5,30,25,6);if(n%5==0){g.drawLine(px-11,py+13,px-22,py-18,5);g.drawLine(px+11,py+13,px+23,py-12,5);}}
}
void BattleEditor::paint(juce::Graphics& g){g.fillAll(col(0x080d17));int w=getWidth(),h=getHeight();if(menu){text(g,"FL_BattleGrounds27",{30,17,float(w-60),48},38,col(0xf0e4ff),juce::Justification::centredLeft);text(g,"ONE ROUND. 30 SECONDS. WIN THE CROWD.",{30,66,float(w-60),25},15,col(0xbcb3ce),juce::Justification::centredLeft);
 stage(g,{30,103,float(w-60),160},true);float cw=float(w-100)/4;for(int i=0;i<4;++i){auto& mc=battle::mcs[size_t(i)];float x=30+i*(cw+13),top=282,bottom=float(h-225);auto c=col(mc.colour);g.setColour(col(processor.home.load()==i?0x262039:0x141b2a));g.fillRoundedRectangle(x,top,cw-8,bottom-top,10);g.setColour(c);g.drawRoundedRectangle(x,top,cw-8,bottom-top,10,processor.home.load()==i?3.f:1.f);
 text(g,mc.name,{x+10,top+12,cw-28,26},23,c);text(g,juce::String(mc.overall)+" OVR",{x+10,top+45,cw-28,38},31,juce::Colours::white);rapper(g,x+cw*.5f,top+139,.46f,i,false,0);text(g,"FLOW "+juce::String(mc.flow)+"   HUMOR "+juce::String(mc.humor),{x+8,bottom-74,cw-24,22},13,col(0xebe6f4));text(g,"ATTACK "+juce::String(mc.attack),{x+8,bottom-50,cw-24,22},13,col(0xebe6f4));text(g,mc.style,{x+8,bottom-25,cw-24,18},10,c);}
 text(g,"OPPONENT",{30,float(h-155),260,22},13,col(0xbcb3ce),juce::Justification::centredLeft);text(g,"DIFFICULTY",{310,float(h-155),320,22},13,col(0xbcb3ce),juce::Justification::centredLeft);
 text(g,"Tap W A S D as notes reach the rings. Build streaks. P pauses.",{30,float(h-82),float(w-60),25},15,col(0xf0e4ff));
 }else drawGame(g);text(g,"Bundled synthetic vocals + original beat",{145,float(h-44),430,24},12,col(0x918ba5),juce::Justification::centredLeft);text(g,"GAME VOLUME",{float(w-355),float(h-43),120,24},12,col(0xaaa1bd));}
void BattleEditor::drawGame(juce::Graphics& g){float w=float(getWidth()),h=float(getHeight());auto home=col(battle::mcs[size_t(game.home)].colour),away=col(battle::mcs[size_t(game.away)].colour);text(g,"FL_BattleGrounds27",{280,12,w-560,33},22,col(0xf0e4ff));text(g,juce::String(std::max(0,int(std::ceil(30-game.time))))+" SEC",{w-190,12,170,32},24,col(0xffdf7c));
 text(g,juce::String(battle::mcs[size_t(game.home)].name)+"  "+juce::String(game.points[0]),{25,51,w*.4f,28},22,home,juce::Justification::centredLeft);text(g,juce::String(game.points[1])+"  "+battle::mcs[size_t(game.away)].name,{w*.55f,51,w*.42f,28},22,away,juce::Justification::centredRight);
 float meterX=30,meterY=91,meterW=w-60;g.setColour(away);g.fillRoundedRectangle(meterX,meterY,meterW,15,5);g.setColour(home);g.fillRoundedRectangle(meterX,meterY,meterW*float(game.crowd()),15,5);g.setColour(juce::Colours::white);g.fillRect(meterX+meterW*float(game.crowd())-2,meterY-3,4.f,21.f);text(g,"CROWD CONTROL",{w*.4f,109,w*.2f,16},11,col(0xb7adc9));
 stage(g,{20,132,w-40,240},false);text(g,juce::String(battle::mcs[size_t(game.activeMC())].name)+(game.activeSide()==0?" / YOUR TURN":" / OPPONENT TURN - WATCH"),{60,338,w-120,30},17,game.activeSide()==0?home:away);
 g.setColour(col(0x171d2c));g.fillRoundedRectangle(30,381,w-60,57,8);text(g,battle::mcs[size_t(game.activeMC())].bars[size_t(game.barIndex())],{45,389,w-90,40},20,col(0xf2e8ff));
 float top=454,bottom=h-90,topW=170,bottomW=480,cx=w*.5f;juce::Path highway;highway.startNewSubPath(cx-topW/2,top);highway.lineTo(cx+topW/2,top);highway.lineTo(cx+bottomW/2,bottom+12);highway.lineTo(cx-bottomW/2,bottom+12);highway.closeSubPath();g.setColour(col(0x151b2b));g.fillPath(highway);
 auto pos=[&](int lane,double ahead){float f=float(juce::jlimit(0.,1.,1-ahead/1.7));f*=f;float width=topW+(bottomW-topW)*f;return juce::Point<float>(cx+((lane+.5f)/4-.5f)*width,top+(bottom-top)*f);};
 for(int i=0;i<=4;++i){g.setColour(col(0x52486a));g.drawLine(cx+(i/4.f-.5f)*topW,top,cx+(i/4.f-.5f)*bottomW,bottom+12,1);}
 for(auto& n:game.notes){double ahead=n.at-game.time;if(n.judged||ahead<-.12||ahead>1.7)continue;auto p=pos(n.lane,ahead);float radius=9+float(1-ahead/1.7)*10;auto c=col(colours[n.lane]);g.setColour(c.withAlpha(n.side==0?1.f:.5f));g.fillEllipse(p.x-radius,p.y-radius,radius*2,radius*2);g.setColour(juce::Colours::white.withAlpha(.5f));g.drawEllipse(p.x-radius+3,p.y-radius+3,radius*2-6,radius*2-6,1);}
 for(int lane=0;lane<4;++lane){auto p=pos(lane,0);auto c=col(colours[lane]);g.setColour(c);g.drawEllipse(p.x-26,p.y-26,52,52,3);if(held[size_t(lane)]||(game.flashLane==lane&&game.time<game.flashUntil)){g.setColour(c.withAlpha(.5f));g.fillEllipse(p.x-23,p.y-23,46,46);}text(g,juce::String::charToString(char(keys[lane])),{p.x-20,p.y-17,40,34},25,c);}
 text(g,"STREAK",{25,470,220,23},13,col(0x9a8fad));text(g,juce::String(game.combo[0]),{25,495,220,50},42,home);text(g,"x"+juce::String(1+std::min(3,game.combo[0]/8))+" FLOW MULTIPLIER",{25,550,220,24},13,col(0xf6d07b));text(g,"BEST "+juce::String(game.best[0]),{25,580,220,23},13,col(0xaba0bb));
 if(game.time<game.feedbackUntil)text(g,game.feedback,{w-270,485,245,65},18,col(0xffdf7c));text(g,"HITS "+juce::String(game.hits[0])+"  MISSES "+juce::String(game.misses[0]),{w-275,566,245,25},13,col(0xb2a6c3));
 if(processor.isPaused()||game.finished){g.setColour(juce::Colours::black.withAlpha(.87f));g.fillRoundedRectangle(w*.18f,450,w*.64f,190,14);text(g,game.finished?game.feedback:"PAUSED",{w*.2f,470,w*.6f,48},27,col(0xffdf7c));text(g,game.finished?juce::String(game.points[0])+" FLOW POINTS  vs  "+juce::String(game.points[1]):"Click the game, then RESUME or press P",{w*.2f,530,w*.6f,28},18,juce::Colours::white);text(g,game.finished?"CHOOSE MC to battle again":"W A S D / tap at the rings",{w*.2f,577,w*.6f,25},15,col(0xb4a7ce));}
}
